export const actions = {
    LAYOUT_ENABLE_NAVIGATION: "LAYOUT_ENABLE_NAVIGATION",
    LAYOUT_DISABLE_NAVIGATION: "LAYOUT_DISABLE_NAVIGATION",
    LAYOUT_ENABLE_NAVIGATION_TOP: "LAYOUT_ENABLE_NAVIGATION_TOP",
    LAYOUT_DISABLE_NAVIGATION_TOP: "LAYOUT_DISABLE_NAVIGATION_TOP",
    LAYOUT_ENABLE_NAVIGATION_BOTTOM: "LAYOUT_ENABLE_NAVIGATION_BOTTOM",
    LAYOUT_DISABLE_NAVIGATION_BOTTOM: "LAYOUT_DISABLE_NAVIGATION_BOTTOM",
}