export const actions = {
    PAGE_ACTION_MODAL_LOGIN: "PAGE_ACTION_MODAL_LOGIN",
    PAGE_HIDE_MODAL_LOGIN: "PAGE_HIDE_MODAL_LOGIN",
    PAGE_SET_CURR_USER: "PAGE_SET_CURR_USER",
    PAGE_GET_CURR_USER: "PAGE_GET_CURR_USER",
}