export const actions = {
    RESPONSIVE_SET_DESKTOP_SCREEN: "RESPONSIVE_DESKTOP_SCREEN",
    RESPONSIVE_SET_MOBILE_SCREEN: "RESPONSIVE_SET_MOBILE_SCREEN",
    RESPONSIVE_SET_TABLET_SCREEN: "RESPONSIVE_SET_TABLET_SCREEN",
}